Feature/add shipment cost
fond-of/spryker-shipment-table-rate pull request #2
Opened 2019-11-22 14:51 UTC by gengjozsef

2019-11-22 14:53 UTC, DerCalli approved these changes
Sieht für mich in Ordnung aus.

2019-11-22 14:59 UTC, sourcecube approved these changes

2019-11-22 15:01 UTC, DerCalli requested changes
change "mikey179/vfsStream": "^1.6" to "mikey179/vfsstream": "^1.6 in composer.json

2019-11-27 08:37 UTC, DerCalli approved these changes

2019-11-27 08:48 UTC, merged